project_id = "plbtnltcocsuekifddat"

[db.seed]
enabled = true
sql_paths = ["./seeds/locations-v1.sql"]

[functions.start-listing-payment]
verify_jwt = false

[functions.verify-listing-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false
