const USE_DEMO_DATA=true,N=Date.now(),Dy=864e5,$=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cedi=n=>'GH₵ '+new Intl.NumberFormat('en-GH',{maximumFractionDigits:0}).format(n);
const listingPricingInfo=l=>{const pricing=window.NestGHListingPricing?.getListingPricing({listingType:l.listingType,category:l.category,type:l.type});return pricing?{type:window.NestGHListingPricing.LISTING_LABELS[pricing.listingType],fee:window.NestGHListingPricing.formatListingPrice(pricing)}:{type:"Not available",fee:"Not available"}};
const fd=t=>new Date(t).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const rel=t=>{const m=Math.round((N-t)/6e4);return m<60?m+' min ago':m<1440?Math.round(m/60)+' hours ago':Math.round(m/1440)+' days ago'};
const P={menu:'M4 6h16M4 12h16M4 18h16',home:'M3 11l9-8 9 8M5 10v10h14V10',building:'M4 21V5l8-3v19M20 21V10l-8-2M8 8h1M8 12h1M8 16h1M16 13h1M16 17h1',users:'M16 20v-1a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v1M9.5 11a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7M21 20v-1a4 4 0 0 0-3-3.9M16 4.1a3.5 3.5 0 0 1 0 6.8',card:'M2 6h20v12H2zM2 10h20',flag:'M5 21V4M5 4h13l-2 4 2 4H5',more:'M12 6h.01M12 12h.01M12 18h.01',search:'M11 18a7 7 0 1 0 0-14 7 7 0 0 0 0 14M21 21l-4-4',bell:'M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9M10 21h4',gear:'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2',plus:'M12 5v14M5 12h14',check:'M5 12l5 5L20 7',x:'M6 6l12 12M18 6L6 18',clock:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18M12 7v5l3 2',alert:'M12 3l10 18H2zM12 10v4M12 18h.01',shield:'M12 3l8 3v6c0 5-4 8-8 9-4-1-8-4-8-9V6z',copy:'M8 8h12v12H8zM4 16V4h12',msg:'M4 5h16v11H9l-5 4z',help:'M4 14v-2a8 8 0 0 1 16 0v2M4 14h3v5H4zM17 14h3v5h-3z',store:'M4 9l1-5h14l1 5M4 9v11h16V9M9 20v-6h6v6',bed:'M3 18V6M3 14h18v4M21 14v-3a3 3 0 0 0-3-3h-7v6',briefcase:'M3 8h18v12H3zM8 8V5h8v3',chev:'M6 9l6 6 6-6',cal:'M4 6h16v14H4zM4 10h16M8 3v4M16 3v4'};
const ic=n=>n=='₵'?'<span style="font-size:20px">₵</span>':`<svg class="svg" viewBox="0 0 24 24" aria-hidden="true"><path d="${P[n]||P.more}"/></svg>`;
function demo(){let s=11;const r=()=>(s=s*16807%2147483647)/2147483647,pk=a=>a[Math.floor(r()*a.length)];
const T=[["Accra","Greater Accra",5.6037,-.187],["Kumasi","Ashanti",6.6885,-1.6244],["Takoradi","Western",4.8962,-1.7554],["Cape Coast","Central",5.1053,-1.2466],["Tarkwa","Western",5.3018,-1.9937],["East Legon","Greater Accra",5.635,-.155],["Madina","Greater Accra",5.668,-.166],["Adenta","Greater Accra",5.707,-.164],["Kasoa","Central",5.534,-.418],["Tamale","Northern",9.4034,-.8424]];
const Y=[["Apartment","building",3800,"2 Bedroom Apartment"],["Room","bed",900,"Single Room"],["House","home",5200,"3 Bedroom House"],["Hostel","bed",1500,"Hostel Room"],["Shop","store",2400,"Shop Space"],["Office","briefcase",3200,"Office Suite"],["Showroom","store",6000,"Showroom"],["Warehouse","building",5000,"Warehouse"],["Salon","store",1800,"Salon Space"],["Restaurant","store",4000,"Restaurant Space"],["Commercial Space","copy",3500,"Commercial Space"],["Other","more",1200,"Property"]];
const L=Array.from({length:72},(_,i)=>{const t=T[Math.floor(r()**1.6*10)],y=Y[Math.floor(r()**1.5*12)],q=r();return{id:i+1,title:y[3]+" – "+t[0],town:t[0],region:t[1],type:y[0],ic:y[1],price:Math.round(y[2]*(.7+r()*.8)/50)*50,status:q<.62?"active":q<.8?"pending":q<.9?"rejected":"suspended",created:N-r()*75*Dy,available:r()<.76,confirmed:N-r()*9*Dy,updated:N-r()*14*Dy,imageUrl:null}});
const U=Array.from({length:160},()=>{const q=r();return{role:q<.65?"Seeker":q<.93?"Owner":"Agent",verified:r()<.74,created:N-r()*75*Dy}});
const Pm=Array.from({length:40},()=>{const q=r();return{amt:pk([50,100,150,200,300]),st:q<.8?"ok":q<.92?"wait":"fail",at:N-r()*180*Dy}});
const R=Array.from({length:16},()=>({k:pk(["rep","sus","dup"]),at:N-r()*14*Dy}));
const S=Array.from({length:70},()=>({k:pk(["owner","user","comp","tick"]),open:r()<.3,at:N-r()*14*Dy}));
return{T,Y,L,U,P:Pm,R,S}}
const D=USE_DEMO_DATA?demo():null,wait=()=>new Promise(r=>setTimeout(r,200+Math.random()*200));
const gr=(a,k,d,f=()=>1)=>{const c=a.filter(x=>f(x)&&x[k]>N-d*Dy).length,p=a.filter(x=>f(x)&&x[k]<=N-d*Dy&&x[k]>N-2*d*Dy).length;return p?Math.round((c-p)/p*100):null};
const sm=(a,lo,hi)=>a.filter(x=>x.st=="ok"&&x.at>N-hi*Dy&&x.at<=N-lo*Dy).reduce((t,x)=>t+x.amt,0);
const pcts=a=>{const t=a.reduce((x,y)=>x+y,0);if(!t)return a.map(()=>0);const f=a.map(v=>v*100/t),b=f.map(Math.floor);let k=100-b.reduce((x,y)=>x+y,0);f.map((v,i)=>[v-b[i],i]).sort((x,y)=>y[0]-x[0]).slice(0,k).forEach(x=>b[x[1]]++);return b};
const cnt=(a,f)=>a.filter(f).length,tally=(a,k)=>{const m={};a.forEach(x=>m[x[k]]=(m[x[k]]||0)+1);return Object.entries(m).sort((x,y)=>y[1]-x[1])};
/* Service layer: swap these functions for NestGH API (MySQL) calls later. UI never touches D directly. */
const svc={
async kpis(){await wait();if(!D)return;const{L,U,P}=D,rev=sm(P,0,1e4),c=sm(P,0,30),p=sm(P,30,60);return[{l:"Total Listings",v:L.length,i:"building",c:"var(--blue)",d:gr(L,"created",30)},{l:"Total Users",v:U.length,i:"users",c:"var(--pu)",d:gr(U,"created",30)},{l:"Total Listing Revenue",v:cedi(rev),i:"₵",c:"var(--gold)",d:p?Math.round((c-p)/p*100):null},{l:"Active Listings",v:cnt(L,x=>x.status=="active"),i:"check",c:"var(--ok)",d:gr(D.L,"created",30,x=>x.status=="active")}]},
async mod(){await wait();if(!D)return;const c=s=>cnt(D.L,x=>x.status==s);return{c:[c("pending"),c("active"),c("rejected"),c("suspended")],q:D.L.filter(x=>x.status=="pending").sort((a,b)=>b.created-a.created).slice(0,3)}},
async users(){await wait();if(!D)return;const{U}=D,v=cnt(U,u=>u.verified);return{n:["Seeker","Owner","Agent"].map(k=>cnt(U,u=>u.role==k)),v,t:U.length-v,p:Math.round(v/U.length*100)}},
async pay(){await wait();if(!D)return;const{P}=D,a=["ok","wait","fail"].map(k=>P.filter(x=>x.st==k).reduce((t,x)=>t+x.amt,0));return{tot:a.reduce((x,y)=>x+y,0),a,p:pcts(a),tr:[5,4,3,2,1,0].map(m=>sm(P,m*30,m*30+30))}},
async rep(){await wait();if(!D)return;return["rep","sus","dup"].map(k=>({n:cnt(D.R,x=>x.k==k),d:gr(D.R,"at",7,x=>x.k==k)}))},
async avail(){await wait();if(!D)return;const{L}=D,a=cnt(L,x=>x.available);return{a,u:L.length-a,p:Math.round(a/L.length*100),days:Math.round(L.reduce((t,x)=>t+(N-x.confirmed),0)/L.length/Dy),rec:cnt(L,x=>x.updated>N-7*Dy)}},
async loc(){await wait();if(!D)return;const{L}=D,rg=tally(L,"region"),top=rg.slice(0,4),oth=rg.slice(4).reduce((t,x)=>t+x[1],0),regs=oth?[...top,["Other",oth]]:top,pc=pcts(regs.map(x=>x[1])),tw=tally(L,"town"),t9=tw.slice(0,9),to=tw.slice(9).reduce((t,x)=>t+x[1],0);return{regs:regs.map((x,i)=>[x[0],x[1],pc[i]]),towns:[...t9,...(to?[["Others",to]]:[])]}},
async cats(){await wait();if(!D)return;return D.Y.map(y=>[y[0],y[1],cnt(D.L,x=>x.type==y[0])])},
async sup(){await wait();if(!D)return;const f=(k)=>({n:cnt(D.S,x=>x.k==k),d:gr(D.S,"at",7,x=>x.k==k)});return{r:[f("owner"),f("user"),f("comp"),f("tick")],open:cnt(D.S,x=>x.open)}},
async recent(){await wait();if(!D)return;return D.L.slice().sort((a,b)=>b.created-a.created).slice(0,6)},
async map(){await wait();if(!D)return;const tw=tally(D.L,"town"),cn=Object.fromEntries(tw);return{pts:["Accra","Kumasi","Takoradi","Cape Coast","Tarkwa"].map(n=>{const t=D.T.find(x=>x[0]==n);return[n,t[2],t[3],cn[n]||0]}),leg:tw.slice(0,9)}},
async set(id,st){await wait();if(!D)return;const l=D.L.find(x=>x.id==id);if(l)l.status=st}};
/* UI helpers */
const CL={active:"var(--ok)",pending:"var(--wa)",rejected:"var(--er)",suspended:"var(--sl)"},LB={active:"Active",pending:"Pending",rejected:"Rejected",suspended:"Suspended"};
const bd=s=>`<span class="bg" style="--c:${CL[s]}">${LB[s]}</span>`;
const chip=(i,c)=>`<span class="chip" style="--c:${c}">${ic(i)}</span>`;
const tile=(l,v,c,i)=>`<div class="tile" style="--c:${c}">${i?`<span class="ti">${ic(i)}</span>`:''}<span>${esc(l)}</span><b>${esc(v)}</b></div>`;
const dl=(d,t)=>d==null?'':`<div class="dl ${d<0?'dn':'up'}">${d<0?'↓':'↑'} ${Math.abs(d)}% ${t}</div>`;
const th=l=>l.imageUrl?`<img class="th" src="${esc(l.imageUrl)}" alt="">`:`<span class="th">${ic(l.ic)}</span>`;
const bar=(l,v,p,c)=>`<div class="row b"><div style="display:flex;justify-content:space-between"><span>${esc(l)}</span><span><b>${v}</b> <span class="mu">${p}%</span></span></div><div class="pb" style="--c:${c};margin-top:6px"><i style="width:${p}%"></i></div></div>`;
const row=(i,c,l,v,d)=>`<div class="row"><span class="l">${chip(i,c)}<span>${l}</span></span><span style="text-align:right"><b>${v}</b>${d||''}</span></div>`;
const donut=(p,l,c='var(--ok)',s=96)=>`<svg viewBox="0 0 36 36" width="${s}" height="${s}" role="img" aria-label="${l}"><circle cx="18" cy="18" r="15.9155" fill="none" stroke="var(--bd)" stroke-width="4"/><circle cx="18" cy="18" r="15.9155" fill="none" stroke="${c}" stroke-width="4" stroke-dasharray="${p} ${100-p}" transform="rotate(-90 18 18)"/><text x="18" y="20" text-anchor="middle" font-size="7" font-weight="700" fill="currentColor">${p}%</text></svg>`;
const W=[
{id:"kpis",bare:1,s:16,f:()=>svc.kpis(),r:k=>`<div class="kp">${k.map((x,i)=>`<div class="card" style="--i:${i}"><div class="kpi">${chip(x.i,x.c)}<div><div class="mu">${x.l}</div><div class="big">${esc(x.v)}</div>${dl(x.d,'vs last 30 days')}</div></div></div>`).join('')}</div>`},
{id:"qa",t:"Quick Actions",nl:1,s:8,f:async()=>1,r:()=>`<div class="qa">${[["plus","Add Listing","var(--blue)"],["users","View Users","var(--pu)"],["card","View Payments","var(--ok)"],["gear","Settings","var(--sl)"]].map(x=>`<a href="#" data-soon>${chip(x[0],x[2])}${x[1]}</a>`).join('')}</div>`},
{id:"mod",t:"Listing Moderation",s:6,f:()=>svc.mod(),r:m=>`<div class="tiles" style="--n:4">${[["Pending",0,"var(--wa)","clock"],["Approved",1,"var(--ok)","check"],["Rejected",2,"var(--er)","x"],["Suspended",3,"var(--sl)","alert"]].map(x=>tile(x[0],m.c[x[1]],x[2],x[3])).join('')}</div>`+(m.q.length?m.q.map(l=>{const p=listingPricingInfo(l);return`<div class="q">${th(l)}<div><b>${esc(l.title)}</b><span class="mu sm">${cedi(l.price)}/month · ${esc(l.type)} · ${p.type} · Listing fee ${p.fee} · ${rel(l.created)}</span><div style="display:flex;gap:6px;margin-top:6px;flex-wrap:wrap"><button class="btn p" data-a="approve" data-id="${l.id}">Approve</button><button class="btn" data-a="reject" data-id="${l.id}">Reject</button><button class="btn" data-a="view" data-id="${l.id}">View</button></div></div></div>`}).join(''):'<p class="mu">No pending listings. The queue is clear.</p>')},
{id:"users",t:"User & Owner Management",s:6,f:()=>svc.users(),r:u=>`<div class="tiles" style="--n:3">${tile("Seekers",u.n[0],"var(--blue)","users")}${tile("Owners",u.n[1],"var(--gold)","home")}${tile("Agents",u.n[2],"var(--pu)","briefcase")}</div>${bar("Verified Users",u.v,u.p,"var(--ok)")}${bar("Pending Verification",u.t,100-u.p,"var(--wa)")}`},
{id:"pay",t:"Payments & Revenue",s:6,f:()=>svc.pay(),r:p=>{const mx=Math.max(...p.tr,1);return`<div class="mu sm">Total Listing Fees (all attempts)</div><div class="big">${cedi(p.tot)}</div><div class="tiles" style="--n:3;margin-top:10px">${[["Successful","var(--ok)","check"],["Pending","var(--wa)","clock"],["Failed","var(--er)","x"]].map((x,i)=>tile(x[0],cedi(p.a[i])+" · "+p.p[i]+"%",x[1],x[2])).join('')}</div><svg viewBox="0 0 120 40" width="100%" height="64" role="img" aria-label="Successful revenue, last 6 months, oldest first: ${p.tr.map(cedi).join(', ')}">${p.tr.map((v,i)=>`<rect x="${i*20+3}" y="${38-v/mx*34}" width="14" height="${Math.max(v/mx*34,1)}" rx="3" fill="var(--blue)" opacity="${.35+i*.13}"/>`).join('')}</svg><p class="mu sm" style="margin:6px 0 0">Payment verification is not connected yet.</p>`}},
{id:"rep",t:"Reports & Fraud",s:6,f:()=>svc.rep(),r:r=>[["alert","var(--er)","Reported Listings"],["shield","var(--pu)","Suspicious Activity"],["copy","var(--wa)","Duplicate Listings"]].map((x,i)=>row(x[0],x[1],x[2],r[i].n,dl(r[i].d,'vs last 7 days'))).join('')},
{id:"avail",t:"Availability & Freshness",s:5,f:()=>svc.avail(),r:a=>`<div class="tiles" style="--n:2">${[["Available",a.a,a.p,"var(--ok)"],["Unavailable",a.u,100-a.p,"var(--sl)"]].map(x=>`<div class="tile" style="--c:${x[3]};text-align:center">${donut(x[2],x[2]+'% '+x[0].toLowerCase(),x[3],64)}<span style="display:block">${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>${row("clock","var(--blue)","Last confirmed (avg.)",a.days+" days ago")}${row("check","var(--ok)","Recently updated (7 days)",a.rec)}`},
{id:"loc",t:"Location & Market Analytics",s:8,f:()=>svc.loc(),r:l=>`<div class="two"><div><h3>Top Regions</h3>${l.regs.map((x,i)=>bar(x[0],x[1],x[2],["var(--r1)","var(--r2)","var(--r3)","var(--r4)","var(--r5)"][i])).join('')}</div><div><h3>Top Towns / Areas</h3>${l.towns.map(x=>`<div class="row"><span>${esc(x[0])}</span><b>${x[1]}</b></div>`).join('')}</div></div>`},
{id:"cats",t:"Property & Category Management",s:6,f:()=>svc.cats(),r:c=>`<div class="tiles" style="--n:3">${c.map(x=>tile(x[0],x[2],"var(--blue)",x[1])).join('')}</div><a href="#" data-soon class="lnk sm">Manage Categories</a>`},
{id:"sup",t:"Support & Messages",s:5,f:()=>svc.sup(),r:s=>[["msg","var(--blue)","Owner Enquiries"],["users","var(--pu)","User Enquiries"],["alert","var(--er)","Complaints"],["help","var(--ok)","Support Tickets"]].map((x,i)=>row(x[0],x[1],x[2],s.r[i].n,dl(s.r[i].d,'vs last 7 days'))).join('')+row("clock","var(--wa)","Unresolved Issues",s.open)},
{id:"recent",t:"Recent Listings",s:16,w:1,f:()=>svc.recent(),r:r=>`<table class="t"><caption class="vh">Recent listings</caption><thead><tr>${["Image","Title","Location","Property type","Listing type","Rent","Listing fee","Status","Listed On","Actions"].map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${r.map(l=>{const p=listingPricingInfo(l);return`<tr><td data-l="Image">${th(l)}</td><td data-l="Title"><b>${esc(l.title)}</b></td><td data-l="Location">${esc(l.town)}, ${esc(l.region)}</td><td data-l="Property type">${esc(l.type)}</td><td data-l="Listing type">${p.type}</td><td data-l="Rent">${cedi(l.price)} <span class="mu sm">/ month</span></td><td data-l="Listing fee">${p.fee}</td><td data-l="Status">${bd(l.status)}</td><td data-l="Listed On">${fd(l.created)}</td><td data-l="Actions"><div class="rel"><button class="ib" data-m aria-haspopup="true" aria-expanded="false" aria-label="Actions for ${esc(l.title)}">${ic('more')}</button><div class="pop" hidden>${[["view","View"],["approve","Approve"],["reject","Reject"],["suspend","Suspend"]].map(a=>`<button data-a="${a[0]}" data-id="${l.id}">${a[1]}</button>`).join('')}</div></div></td></tr>`}).join('')}</tbody></table>`},
{id:"map",t:"Listings by Location",s:8,w:1,f:()=>svc.map(),r:m=>{const mx=Math.max(...m.pts.map(p=>p[3]),1),X=g=>(g+2.3)/2.6*280+10,Y=a=>(6.9-a)/2.2*230+15;return`<svg viewBox="0 0 300 260" width="100%" role="img" aria-label="Sample listing counts: ${m.pts.map(p=>p[0]+' '+p[3]).join(', ')}" style="background:var(--bg);border-radius:12px">${[0,1,2,3,4,5].map(i=>`<path d="M${10+i*56} 15v230M10 ${15+i*46}h280" stroke="var(--bd)"/>`).join('')}${m.pts.map(p=>{const r=11+p[3]/mx*10;return`<circle cx="${X(p[2])}" cy="${Y(p[1])}" r="${r}" fill="var(--blue)" stroke="#fff" stroke-width="2"/><text x="${X(p[2])}" y="${Y(p[1])+4}" text-anchor="middle" font-size="11" font-weight="700" fill="#fff">${p[3]}</text><text x="${X(p[2])+r+3}" y="${Y(p[1])+4}" font-size="12" fill="currentColor">${esc(p[0])}</text>`}).join('')}</svg><p class="mu sm" style="margin:6px 0">Positions use real coordinates. Map tiles load in the live app.</p><div class="two" style="gap:0 16px">${m.leg.map(x=>`<div class="row" style="padding:5px 0"><span>${esc(x[0])}</span><b>${x[1]}</b></div>`).join('')}</div>`}}];
async function load(el,fn,rd,q){if(!q)el.innerHTML='<div class="sk"></div><div class="sk"></div>';try{const d=await fn();if(d==null){el.innerHTML='<p class="mu">Nothing to show yet.</p>';return}el.innerHTML=rd(d);el.querySelectorAll('i[data-i]').forEach(e=>e.outerHTML=ic(e.dataset.i))}catch(e){el.innerHTML='<p class="mu">We couldn\'t load this. <button class="lnk">Try Again</button></p>';el.querySelector('button').onclick=()=>load(el,fn,rd)}}
const run=q=>W.forEach(w=>load($('#w-'+w.id),w.f,w.r,q));
W.forEach((w,i)=>$('#g').insertAdjacentHTML('beforeend',w.bare?`<div class="c" style="--s:${w.s}"><div id="w-${w.id}"></div></div>`:`<section class="card c${w.w?' w':''}" style="--s:${w.s};--i:${i}" aria-label="${w.t}"><div class="hd"><h2>${w.t}</h2>${w.nl?'':'<a href="#" data-soon>View all →</a>'}</div><div id="w-${w.id}"></div></section>`));
document.querySelectorAll('i[data-i]').forEach(e=>e.outerHTML=ic(e.dataset.i));run();
/* Interactions */
let tt,pend,nav=$('#nav'),mb=$('#mb'),bk=$('#bk');
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('on');clearTimeout(tt);tt=setTimeout(()=>e.classList.remove('on'),2600)};
const dr=o=>{nav.classList.toggle('open',o);bk.hidden=!o;mb.setAttribute('aria-expanded',o);o?nav.querySelector('a').focus():mb.focus()};
const done=()=>{toast('Demo mode: change not saved');run(true)};
async function act(a,id){if(a=='view')return toast('Demo mode: no detail page in this preview');if(a=='reject'){pend=id;$('#why').value='';return $('#dlg').showModal()}await svc.set(id,a=='approve'?'active':'suspended');done()}
mb.onclick=()=>dr(true);bk.onclick=()=>dr(false);$('#no').onclick=()=>$('#dlg').close();$('#yes').onclick=async()=>{$('#dlg').close();await svc.set(pend,'rejected');done()};
document.addEventListener('click',e=>{const m=e.target.closest('[data-m]');document.querySelectorAll('.pop').forEach(p=>{if(!m||p!==m.nextElementSibling)p.hidden=true});if(m)m.nextElementSibling.hidden=!m.nextElementSibling.hidden;document.querySelectorAll('[data-m]').forEach(b=>b.setAttribute('aria-expanded',!b.nextElementSibling.hidden));if(m)return;const s=e.target.closest('[data-soon]');if(s){e.preventDefault();toast('Not part of this preview yet')}const a=e.target.closest('[data-a]');if(a)act(a.dataset.a,+a.dataset.id)});
document.addEventListener('keydown',e=>{if(e.key=='Escape'){document.querySelectorAll('.pop').forEach(p=>p.hidden=true);if(nav.classList.contains('open'))dr(false)}
if(e.key=='Tab'&&nav.classList.contains('open')){const f=[...nav.querySelectorAll('a,button')],i=f.indexOf(document.activeElement);if(e.shiftKey&&i<=0){f[f.length-1].focus();e.preventDefault()}else if(!e.shiftKey&&i==f.length-1){f[0].focus();e.preventDefault()}}});

const html=document.documentElement,tb=$('#th'),setB=b=>{html.dataset.brand=b;tb.setAttribute('aria-pressed',b=='gold');tb.textContent=b=='gold'?'Gold theme: on':'Gold theme';try{localStorage.setItem('nestgh-brand',b)}catch(e){}};
let sb='ref';try{sb=localStorage.getItem('nestgh-brand')||'ref'}catch(e){}
setB(sb);tb.onclick=()=>setB(html.dataset.brand=='gold'?'ref':'gold');